Update url_screenshot_check.py
Fixed error due to media error on morphosource end.


Run python .github/scripts/url_screenshot_check.py release_body.txt
11Found 1 MorphoSource URLs in file
12
13Processing URL 1/1: https://www.morphosource.org/concern/media/000699265
14
15Attempt 1/3 for ID 000699265
16Loading URL: https://www.morphosource.org/concern/media/000699265
17Error on attempt 1: Message:
18Stacktrace:
19#0 0x55a700eb58fa <unknown>
20#1 0x55a7009c6d20 <unknown>
21#2 0x55a700a15a66 <unknown>
22#3 0x55a700a15d01 <unknown>
23#4 0x55a700a5b184 <unknown>
24#5 0x55a700a39b1d <unknown>
25#6 0x55a700a58560 <unknown>
26#7 0x55a700a39893 <unknown>
27#8 0x55a700a0830d <unknown>
28#9 0x55a700a0932e <unknown>
29#10 0x55a700e8200b <unknown>
30#11 0x55a700e85f97 <unknown>
31#12 0x55a700e6e71c <unknown>
32#13 0x55a700e86b17 <unknown>
33#14 0x55a700e536cf <unknown>
34#15 0x55a700ea46b8 <unknown>
35#16 0x55a700ea4880 <unknown>
36#17 0x55a700eb4776 <unknown>
37#18 0x7fb573c9ca94 <unknown>
38#19 0x7fb573d29c3c <unknown>
39
40Error screenshot saved as error_000699265.png
41
42Screenshot process complete
43Successfully captured 0 out of 1 screenshots
44Error: Process completed with exit code 1.